### ISSUE TITLE
Compatibility with Firefox

### ISSUE THREAD

**Issue by ljleb** [ModelSurge/sd-webui-comfyui#10]
Sometimes firefox does not render the `<object>` properly:

![image](https://user-images.githubusercontent.com/32277961/226545847-e6f73a27-9c97-4cba-9d09-0ed9187ab635.png)

Additionally, firefox [does not support](https://caniuse.com/?search=has) the css selector `:has()`, which is used at the moment to hide the gradio footer when the ComfyUI tab is selected.

**Comment by John-WL** [comment]
Firefox seems to work now? Is there an issue I don't understand? It does work reliably when I open it on my side now.

**Comment by ljleb** [comment]
I haven't ran into this again. Not sure what it was back then, maybe new versions don't have a problem anymore. I'll close and we can reopen if someone runs into this.

Readme needs to be updated to dash the part about firefox incompatibility.

**Comment by John-WL** [comment]
I'll update readme
