### ISSUE TITLE
Preview Image boinks it all up

### ISSUE THREAD

**Issue by f-rank** [ModelSurge/sd-webui-comfyui#145]
If I add or load a template with Preview Image node(s) in it, it start spewing in console:

[ComfyUI] Failed to validate prompt for output 51:
[ComfyUI] * ImageEffectsAdjustment 50:
[ComfyUI]   - Exception when validating inner node: tuple index out of range
[ComfyUI] * Image Style Filter 42:
[ComfyUI]   - Exception when validating inner node: tuple index out of range
[ComfyUI] Output will be ignored
WARNING: Ignoring invalid distribution -illow (d:\work\conda_envs\automatic\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (d:\work\conda_envs\automatic\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (d:\work\conda_envs\automatic\stable-diffusion-webui\venv\lib\site-packages)
[ComfyUI] Prompt executed in 4.16 seconds

The nodes that get a red contour aren't even the preview one's though. They are whichever that get their connections from the "From Webui - Postprocess" node. This is in txt2img.
Removing the Preview Image nodes makes it all run through.

webui: 1.5.1
sd-webui-comfyui: [947813e7](https://github.com/ModelSurge/sd-webui-comfyui/commit/947813e73d34b3d7fa8046308bdae62dcde08951)

**Comment by ljleb** [comment]
Thanks, should be fixed now. I'm not confident how well this is gonna hold but it seemed to hold well with a relatively intricate workflow.

**Comment by f-rank** [comment]
> Thanks, should be fixed now. I'm not confident how long this is gonna hold since comfyui is frequently updated, but it seemed to work well with a relatively intricate workflow.

Thanks for the fix.
Cross fingers.
