### ISSUE TITLE
[bug] Something wrong with dev branch

### ISSUE THREAD

**Issue by anne43983959** [ModelSurge/sd-webui-comfyui#151]
Something went wrong when I use this extension after I move to the [dev branch](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/bae91855f5270894b21575147e3855c1584fb4d4)
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/115604775/f6b3b717-1724-4ba3-b48f-f20e81fae6de)

environmen info:
python: 3.10.10
torch: 2.0.1+cu118 
xformers: 0.0.20 
gradio: 3.39.0 

extra info:
ComfUI still work properly on http://127.0.0.1:8189/, the only problem is the tab on webui was broken

**Comment by ljleb** [comment]
We likely have a couple incompatibility issues with the next version of the webui indeed. I started looking into it, we have to rewrite some of the monkey patching. It's a lot of complexity, so I think we should consider dropping support for 1.5.1 when 1.6.0 or 1.6.1 goes live.

**Comment by ljleb** [comment]
They renamed the html ids for txt2img elements from `*_txt2txt_*` to `*_txt2img_*` in webui==1.6.0, which the code explicitly relies on to be able to programatically click on them. I won't mention it to them because I'm pretty sure auto won't revert it.
