### ISSUE TITLE
127.0.0.1 refused to connect

### ISSUE THREAD

**Issue by StrangerGithuber** [ModelSurge/sd-webui-comfyui#160]
Hi
When I am clicking to the Comfy UI tab in the Automata1111 then I get "127.0.0.1 refused to connect" however if I go directly to the http://127.0.0.1:8188/ link then comfy ui appears.
Why it happens this?

Thank you in advance for the answers.

Images
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/1939827/467cf5bf-85f1-4ec0-9a14-b5a0a64b0220)
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/1939827/1afb5334-a338-403c-b3da-23ea921ee7d0)

**Comment by John-WL** [comment]
I believe this is due to the webui loading *before* the comfyui server starts. If this happens, I think you can just click the blue button under one of the tabs to reload the iframes, or reload the webui with F5. The tab should appear as intended after that.

**Comment by jasoncow007** [comment]
it's normal yesterday, bu same issue  happed to me today,,,,I tried reload button but still 127.0.0.0 refused to connect,,,, is this related to the new update to comfyui?

> I believe this is due to the webui loading _before_ the comfyui server starts. If this happens, I think you can just click the blue button under one of the tabs to reload the iframes, or reload the webui with F5. The tab should appear as intended after that.

**Comment by John-WL** [comment]
You're right I can reproduce. @ljleb Any clues as to why it's doing that?
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/34081873/9b1b9ce0-92ab-434f-afa6-23cb0e84b6c0)
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/34081873/fde7f3c5-8a3f-4872-88f7-540adcf01254)

Comfy is accessible on its own. I tried switching the reverse proxy setting to "Never", it doesn't work.

**Comment by jasoncow007** [comment]
any idea to resolv this issue?

**Comment by ljleb** [comment]
If this is recent, then probably comfyui update broke something. I'll look into it this weekend

**Comment by one1byte** [comment]
same error in automatic tab, with all this working separately in the tab http://127.0.0.1:8188

**Comment by ljleb** [comment]
Comfyui changed their argument parsing code last week, which is the cause of the bug. I'm working on a workaround

**Comment by Giroyoda** [comment]
The same problem came up again. Is there any way to fix it?

**Comment by John-WL** [comment]
> The same problem came up again. Is there any way to fix it?

I just tested after updating all my extensions (ComfyUI + sd-webui-comfyui), and it works fine for me. Make sure all your extensions/dependencies are up to date. Let us know if the issue still persists.

**Comment by kenny-hash** [comment]
`<iframe base_src="http://127.0.0.1:8189" workflow_type_id="sandbox_tab" src="http://127.0.0.1:8189?workflowTypeId=sandbox_tab&amp;webuiClientId=4350573b-28ac-433d-bbb7-d446f9ab38ae">
</iframe>`

This is the iframe code from inspector, the base_src seems to be my localhost but I run the SD on my server.
To solve this problem, I add a port forward via VScode which forward the serverip:8189 to localhost:8189 and that works for me.
I guess you should modify the code in https://github.com/ModelSurge/sd-webui-comfyui/blob/dfc7fb9fec4faa096c9b8934687035ed627128ae/lib_comfyui/webui/settings.py#L121 to get correct base_src.

Sorry for that I have no idea about the code.

**Comment by ljleb** [comment]
For this, you have to select "Always" in the settings for the parameter about starting a proxy. The code checks for a few flags that are passed to the webui to enable it automatically by default, but sometimes users have a remote server without these flags.

**Comment by Andree11gor** [comment]
I have the same problem with ComfyUI. For some reason Site 127.0.0.1 won't allow a connection to be established. Can you tell me what to fix to start ComfyUI please?
![Screenshot_2](https://github.com/ModelSurge/sd-webui-comfyui/assets/119685449/fff6bd35-d914-46c5-9741-8d209c3d09dd)
![Screenshot_3](https://github.com/ModelSurge/sd-webui-comfyui/assets/119685449/5b68dff7-0b68-41c8-b041-3deb8dae6b15)

**Comment by ljleb** [comment]
@Andree11gor does the command line interface still block at "Patching ComfyUI" if you go to settings, switch the interprocess communication strategy to "File System" and the fully restart the webui?

**Comment by Andree11gor** [comment]
No, the problem remains.
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/119685449/a051d36a-690c-40fd-97df-cb41b1f1b3e9)

**Comment by ljleb** [comment]
Apologies, I think I know the problem. If you read a bit earlier in your logs, the extension warns you that you have `TEMP=tmp` and that this can cause issues on windows. Try the fix proposed later in the same error message.

**Comment by Andree11gor** [comment]
Thank you for your help! So the problem was not solved. I decided to put a separate Comfy)
