### ISSUE TITLE
get “127.0.0.1 connection rejected” when connect via nginx reverse proxy

### ISSUE THREAD

**Issue by Febtw** [ModelSurge/sd-webui-comfyui#165]
I use nginx reverse proxy to connect to the stable diffusion webui, so I don't need to use the -- share or -- ngrok command parameters, nor do I need the sd-webi-tunnels extension.

Perhaps this caused sd-webui-comfyui use wrong ip or domain name, and I received a prompt that 127.0.0.1 connection rejected.

Can sd-webui-comfyui automatically obtain the ip or domain name of the nginx reverse proxy server to load comfyui for remote users?

**Comment by ljleb** [comment]
Does it work if you go in the settings and change the reverse proxy options to "Always"? This will create a reverse proxy in the webui api (the webui needs to be launched with `--api`) and the ui will try to use it to connect to the comfyui server.

**Comment by Febtw** [comment]
> Does it work if you go in the settings and change the reverse proxy options to "Always" in the extension settings (the last one named "Load ComfyUI iframes through a reverse proxy")

Thanks, it works well after I change the reverse proxy options to "Always".

**Comment by Febtw** [comment]
> Does it work if you go in the settings and change the reverse proxy options to "Always" in the extension settings (the last one named "Load ComfyUI iframes through a reverse proxy")? This will create a reverse proxy in the webui api (the webui needs to be launched with `--api`) and the ui will try to use it to connect to the comfyui server.

Thanks, it works well after I change the reverse proxy options to "Always".
