### ISSUE TITLE
Install button for ComfyUI-Manager

### ISSUE THREAD

**Issue by corolorn** [ModelSurge/sd-webui-comfyui#167]
https://github.com/ltdrdata/ComfyUI-Manager
An extremely convenient and pleasant thing to expand the popularity and ease of working with this extension. but I couldn’t figure out how to attach it to SD-Webui-comfyui. Sorry in advance I'm new to this

**Comment by corolorn** [comment]
Sorry, I figured it out. enough in the directory 
automatic1111\extensions\sd-webui-comfyui\comfyui_custom_nodes
use
git clone https://github.com/ltdrdata/ComfyUI-Manager

**Comment by ljleb** [comment]
We planned on adding a button to install it with comfyui. Will keep this open to track completion.

**Comment by John-WL** [comment]
You can install ComfyUI-Manager like you normally would in your ComfyUI installation under `ComfyUI/custom_nodes`. 

I wouldn't recommend adding nodes to `sd-webui-comfyui/comfyui_custom_nodes`, because then you won't load these nodes if you decide to run ComfyUI on its own without the Webui.

**Comment by ljleb** [comment]
> I wouldn't recommend adding nodes to sd-webui-comfyui/comfyui_custom_nodes, because then you won't load these nodes if you decide to run ComfyUI on its own without the Webui.

I did not read correctly. This is correct, but also in my experience many extensions cannot work outside of the normal comfyui custom_nodes folder.
