### ISSUE TITLE
:) AMAZING extention, i just have a question

### ISSUE THREAD

**Issue by 4lt3r3go** [ModelSurge/sd-webui-comfyui#175]
why there are some stuff that are appyed ot top? like face restoreation or Adetailer for example.
I wish there were a way to use Comfy nodes as last step in the chain, the post/pre selector doesnt help in this case here

**Comment by John-WL** [comment]
Hello, thank you for using the extension! I'm glad you like it. 

Regarding your question, I am not sure I fully understand. 

If you want to use ComfyUI nodes to do some post-processing on your image, you can do so by developing ComfyUI accordions in the txt2img and img2img tabs. You can then enable the workflow types that you want, and add some nodes between the `From Webui` and `To Webui` nodes. 

Is this what you are trying to do?

**Comment by John-WL** [comment]
Oh I think I understand. You're right, you cannot have a workflow type as the last step of the chain right now. 

The reason for this is because we are kind of restricted on when to run the workflow types in the Webui. I wonder how easily it could be done right now. 

In the meanwhile, you can always run the pipeline once without ComfyUI, and then pass it to img2img with 0 denoising strength to do your postprocess in the tab. I know it's not very practical like this, but at least it works.

**Comment by John-WL** [comment]
So I just looked, and there is one script callback that could be used for this, `postprocess_images`. 

I think it's somewhat easy to add a workflow type there, but we need to add restrictions on how many `To Webui` nodes can be added (only one in this case), and throw an error otherwise. 

I think it's very doable if we add this restriction feature to the extension's workflow type API.

**Comment by 4lt3r3go** [comment]
thanks for answering... i think i understand why is not possible (probably is the latent to image step).
Yeah in my case i was adding some sharpeness and grain using comfy nodes, but then after the process the adetailers or face restoration kicks in and remove the sharpness and the grain, processing over it. I think you got the "problem" yes...

**Comment by 4lt3r3go** [comment]
so after those comfy nodes the image comes out from the latent space and being processed again AS IMAGE by those face modules, i think is like that i dont know

**Comment by John-WL** [comment]
Yes, I just looked, and basically the face-restore section is right after the extension's callback. So it's just a matter of running the extension at the right moment. 

I actually don't know if we really need to restrict at all the amount of `To Webui` nodes. I'll look into it this week.

**Comment by John-WL** [comment]
I can confirm, this is needed:
> restrictions on how many `To Webui` nodes can be added (only one in this case), and throw an error otherwise.

**Comment by 4lt3r3go** [comment]
forgive me brother, havent really understood what is that "to webui" restriction. It is something i can do? sorry again

**Comment by John-WL** [comment]
> forgive me brother, havent really understood what is that "to webui" restriction. It is something i can do? sorry again

You don't have to do anything about it. I was documenting what needed to change in the issue dedicated to the problem. 
If you are interested in what's going on under the hood, this info could be of interest to you. 
Otherwise, you can ignore my previous comment 👍

**Comment by John-WL** [comment]
I made a PR for this that basically adds a new workflow `Postprocess Image` for processing later in the pipeline. 
There are differences between the `Postprocess` and the new `Postprocess Image` workflows. 

`Postprocess` workflow:
✔️ Can modify the size of the batch
❌ Is **not** the very last thing that runs in the pipeline (but almost)

`Postprocess Image` workflow:
❌ **Cannot** modify the size of the batch
✔️ Runs later in the pipeline (notably **after** Adetailer and FaceRestore)

**Comment by 4lt3r3go** [comment]
GOD BLESS YOU!
(does god exists? i dont think so...whatever)

**Comment by 4lt3r3go** [comment]
WORKS PERFECTLY!! thank you!!! 
 the only problem i still find (this was already happening) is that often when i paste an image the comfy settings are not loaded at all. i see them in the exif, they are pated in the prompt but arent loaded. this wasnt happening the first time i installed this extention... i think i may have broke something. anyway. i just need 2 nodes, they are simple to setup. no worries

**Comment by 4lt3r3go** [comment]
this error in console when i press SAVE image. (images are saved tho)
![231119124451](https://github.com/ModelSurge/sd-webui-comfyui/assets/44883288/7216ea56-4b45-4843-b470-511793ca97c8)

**Comment by John-WL** [comment]
Ah, that's an issue I introduced with the PR indeed. I'll fix this today. 

Thanks for reporting!

**Comment by John-WL** [comment]
>  the only problem i still find (this was already happening) is that often when i paste an image the comfy settings are not loaded at all. 

What do you mean by "comfy settings"? 
Do you mean that the workflow is not being loaded when drag and dropping an image? 
Or something else?

**Comment by 4lt3r3go** [comment]
when i started using this extention and saved some images, then when i was dropping saved images into prompt or PNG info tab to recall all saved settings, the comfyu extention was getting all settings too. This is not happening anymore for some reasons

**Comment by John-WL** [comment]
Oh I think you're running into #112.

**Comment by 4lt3r3go** [comment]
> Oh I think you're running into #112.

i'm becoming autistic (thank you for help) is there a way to setup a workflow as default so is always automatically loaded? 
this is my obsession btw and what is all this post about :D 

[sharp_grain.json](https://github.com/ModelSurge/sd-webui-comfyui/files/13637937/sharp_grain.json)

**Comment by John-WL** [comment]
I think #113 would help with that. If you think overriding the default workflow would still be usefull after #113 is implemented, feel free to open an issue for a feature request!

**Comment by John-WL** [comment]
FYI right now the default workflows are hardcoded in js, so there is no way at the moment.
