### ISSUE TITLE
HTTPS Errors.

### ISSUE THREAD

**Issue by vicitooo** [ModelSurge/sd-webui-comfyui#182]
I'm running AUTO1111 and comfy on a cloud. Since the cloud I use don't start the UIs over HTTPS I get these errors:

![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/41148215/86be821c-f205-439f-9ed5-af350062ca96)

Any ideas for a solution?

**Comment by John-WL** [comment]
Have you tried using the reverse proxy in the settings?
