### ISSUE TITLE
BAG, [WinError 183] File exists: 'ipc_payload_args_webui'

### ISSUE THREAD

**Issue by slavikfoxy** [ModelSurge/sd-webui-comfyui#196]
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[sd-webui-comfyui] Started callback listeners for process webui
[sd-webui-comfyui] Found TEMP="tmp" in the environment. On Windows, this is known to cause issues.
[sd-webui-comfyui] If ComfyUI refuses to start, consider using TEMP="temp" or TMP="temp" as a workaround.
[sd-webui-comfyui] For more information, see https://github.com/ModelSurge/sd-webui-comfyui/issues/170#issuecomment-1792009789
[sd-webui-comfyui] Starting subprocess for comfyui...
Startup time: 2.8s (scripts unloaded callback: 0.5s, load scripts: 0.5s, create ui: 1.6s, gradio launch: 0.1s).
[ComfyUI] [sd-webui-comfyui] Setting up IPC...
[ComfyUI] [sd-webui-comfyui] Using inter-process communication strategy: Shared memory
[ComfyUI] [sd-webui-comfyui] Started callback listeners for process comfyui
Exception in thread Thread-1 (thread_loop):
Traceback (most recent call last):
  File "D:\AI\stable-diffusion-portable-main\python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\AI\stable-diffusion-portable-main\python\lib\threading.py", line 953, in run
[ComfyUI] [sd-webui-comfyui] Patching ComfyUI...
    self._target(*self._args, **self._kwargs)
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\ipc\callback.py", line 27, in thread_loop
    self.attend_consumer(timeout=0.5)
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\ipc\callback.py", line 44, in attend_consumer
    args, kwargs = self._args_receiver.recv(timeout=timeout)
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\ipc\payload.py", line 57, in recv
    with lock as lock_file:
  File "D:\AI\stable-diffusion-portable-main\venv\lib\site-packages\portalocker\utils.py", line 163, in __enter__
    return self.acquire()
  File "D:\AI\stable-diffusion-portable-main\venv\lib\site-packages\portalocker\utils.py", line 258, in acquire
    fh = self._get_fh()
  File "D:\AI\stable-diffusion-portable-main\venv\lib\site-packages\portalocker\utils.py", line 307, in _get_fh
Traceback (most recent call last):
    return open(  # noqa: SIM115
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 98, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\oliyn\\AppData\\Local\\Temp\\ipc_payload_args_comfyui'
    main()
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 43, in main
    patch_comfyui()
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\comfyui\pre_main.py", line 84, in patch_comfyui
    paths.share_webui_folder_paths()
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 41, in wrapper
    return function(*args, **kwargs)
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\webui\paths.py", line 10, in share_webui_folder_paths
    webui_folder_paths = get_webui_folder_paths()
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\ipc\__init__.py", line 20, in wrapper
    res = current_callback_proxies[process_id].get(args=(function.__module__, function.__qualname__, args, kwargs))
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\ipc\callback.py", line 70, in get
    self._args_sender.send((args if args is not None else (), kwargs if kwargs is not None else {}))
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\ipc\payload.py", line 45, in send
    self._strategy.set_data(lock_file, pickle.dumps(value))
  File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\lib_comfyui\ipc\strategies.py", line 98, in set_data
    self._shm = SharedMemory(name=self._shm_name, create=True, size=data_len)
  File "D:\AI\stable-diffusion-portable-main\python\lib\multiprocessing\shared_memory.py", line 143, in __init__
    raise FileExistsError(
FileExistsError: [WinError 183] File exists: 'ipc_payload_args_webui'

**Comment by slavikfoxy** [comment]
To see the GUI go to: http://127.0.0.1:8189
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json
FETCH DATA from: D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json
Install custom node 'nui suite'
install: ['https://github.com/space-nuko/nui-suite']
Download: git clone 'https://github.com/space-nuko/nui-suite'
[!] Traceback (most recent call last):
[!]   File "D:\AI\stable-diffusion-portable-main\venv\lib\site-packages\git\__init__.py", line 89, in <module>
[!]     refresh()
[!]   File "D:\AI\stable-diffusion-portable-main\venv\lib\site-packages\git\__init__.py", line 76, in refresh
[!]     if not Git.refresh(path=path):
[!]   File "D:\AI\stable-diffusion-portable-main\venv\lib\site-packages\git\cmd.py", line 392, in refresh
[!]     raise ImportError(err)
[!] ImportError: Bad git executable.
[!] The git executable must be specified in one of the following ways:
[!]     - be included in your $PATH
[!]     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[!]     - explicitly set via git.refresh()
[!]
[!] All git commands will error until this is rectified.
[!]
[!] This initial warning can be silenced or aggravated in the future by setting the
[!] $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[!]     - quiet|q|silence|s|none|n|0: for no warning or exception
[!]     - warn|w|warning|1: for a printed warning
[!]     - error|e|raise|r|2: for a raised exception
[!]
[!] Example:
[!]     export GIT_PYTHON_REFRESH=quiet
[!]
[!]
[!] The above exception was the direct cause of the following exception:
[!]
[!] Traceback (most recent call last):
[!]   File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\git_helper.py", line 3, in <module>
[!]     import git
[!]   File "D:\AI\stable-diffusion-portable-main\venv\lib\site-packages\git\__init__.py", line 91, in <module>
[!]     raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
[!] ImportError: Failed to initialize: Bad git executable.
[!] The git executable must be specified in one of the following ways:
[!]     - be included in your $PATH
[!]     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[!]     - explicitly set via git.refresh()
[!]
[!] All git commands will error until this is rectified.
[!]
[!] This initial warning can be silenced or aggravated in the future by setting the
[!] $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[!]     - quiet|q|silence|s|none|n|0: for no warning or exception
[!]     - warn|w|warning|1: for a printed warning
[!]     - error|e|raise|r|2: for a raised exception
[!]
[!] Example:
[!]     export GIT_PYTHON_REFRESH=quiet
[!]
FETCH DATA from: D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json
FETCH DATA from: D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json

**Comment by slavikfoxy** [comment]
To see the GUI go to: http://127.0.0.1:8189
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json
FETCH DATA from: D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json
Install custom node 'nui suite'
install: ['https://github.com/space-nuko/nui-suite']
Download: git clone 'https://github.com/space-nuko/nui-suite'
[!] Traceback (most recent call last):
[!]   File "D:\AI\stable-diffusion-portable-main\venv\lib\site-packages\git\__init__.py", line 89, in <module>
[!]     refresh()
[!]   File "D:\AI\stable-diffusion-portable-main\venv\lib\site-packages\git\__init__.py", line 76, in refresh
[!]     if not Git.refresh(path=path):
[!]   File "D:\AI\stable-diffusion-portable-main\venv\lib\site-packages\git\cmd.py", line 392, in refresh
[!]     raise ImportError(err)
[!] ImportError: Bad git executable.
[!] The git executable must be specified in one of the following ways:
[!]     - be included in your $PATH
[!]     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[!]     - explicitly set via git.refresh()
[!]
[!] All git commands will error until this is rectified.
[!]
[!] This initial warning can be silenced or aggravated in the future by setting the
[!] $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[!]     - quiet|q|silence|s|none|n|0: for no warning or exception
[!]     - warn|w|warning|1: for a printed warning
[!]     - error|e|raise|r|2: for a raised exception
[!]
[!] Example:
[!]     export GIT_PYTHON_REFRESH=quiet
[!]
[!]
[!] The above exception was the direct cause of the following exception:
[!]
[!] Traceback (most recent call last):
[!]   File "D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\git_helper.py", line 3, in <module>
[!]     import git
[!]   File "D:\AI\stable-diffusion-portable-main\venv\lib\site-packages\git\__init__.py", line 91, in <module>
[!]     raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
[!] ImportError: Failed to initialize: Bad git executable.
[!] The git executable must be specified in one of the following ways:
[!]     - be included in your $PATH
[!]     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[!]     - explicitly set via git.refresh()
[!]
[!] All git commands will error until this is rectified.
[!]
[!] This initial warning can be silenced or aggravated in the future by setting the
[!] $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[!]     - quiet|q|silence|s|none|n|0: for no warning or exception
[!]     - warn|w|warning|1: for a printed warning
[!]     - error|e|raise|r|2: for a raised exception
[!]
[!] Example:
[!]     export GIT_PYTHON_REFRESH=quiet
[!]
FETCH DATA from: D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json
FETCH DATA from: D:\AI\stable-diffusion-portable-main\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json

**Comment by PladsElsker** [comment]
Closing this because no answer from OP. Do reopen if you still have the issue.
