### ISSUE TITLE
Download ComfyUI for the test pipeline

### ISSUE THREAD

**Issue by John-WL** [ModelSurge/sd-webui-comfyui#20]
Add tests for:
- Downloading a fresh ComfyUI
- Running a freshly downloaded ComfyUI
- Making sure all the cmd args in ComfyUI are handled and forwarded by a1111

**Comment by ljleb** [comment]
Can we close this? Is there anything that the tests lack at the moment?

**Comment by John-WL** [comment]
Yes, we are downloading a fresh webui and sd-webui-comfyui, but we are not launching with a comfyui install. Do you think it makes sense to add it to the pipeline?

**Comment by ljleb** [comment]
It should be part of the test pipeline if we are to add functional tests. It shouldn't be necessary to put everything together for unit tests.

**Comment by John-WL** [comment]
I think we might want to add functional tests for the various nodes and the custom js extension.
