### ISSUE TITLE
How do I make this plug-in through webui api, just like the controlnet plug-in?

### ISSUE THREAD

**Issue by fiy-fiy** [ModelSurge/sd-webui-comfyui#203]

**Comment by John-WL** [comment]
Hi, thanks for your interest in this extension! As of now, there is no api.

**Comment by John-WL** [comment]
Related: #115

**Comment by fiy-fiy** [comment]
> Hi, thanks for your interest in this extension! As of now, there is no api.

thanks! what i want is this-using this plug-in in alwayson_scripts property
Related:https://github.com/ModelSurge/sd-webui-comfyui/issues/115#issuecomment-1674144614

**Comment by John-WL** [comment]
I don't know when this will be implemented, it may take a long time if I look at how much time passed since #115 was opened haha... 

As a suggestion, if you think you know how to implement it yourself, you can always open a PR with the requested changes! We will happily review it.

**Comment by ljleb** [comment]
#115 has been stale because there was no interest for the feature by anyone. Now that there is interest for this, I am considering to look into it. I don't have an ETA but it's on my todo list.

**Comment by ljleb** [comment]
I will close this issue, please refer to #115 to track completion.
