### ISSUE TITLE
How to use ComfyUI in Automatic 1111 (in Colab) 

### ISSUE THREAD

**Issue by ccpong-github** [ModelSurge/sd-webui-comfyui#211]
Hello!

I just have installed ComfyUI in Automatic 1111 (in Google Colab environment). And I saw the "ComfyUI tab" and "ComfyUI option" in "txt2img" Tab. 

However, I cannot see any ComfyUI workflow in any "ComfyUI Tab" and "ComfyUI option" after generating image. 

Please help (and if there is any tutorial reference).

Thanks!

**Comment by PladsElsker** [comment]
Hello, thank you for trying out the extension. 

In order to run on collab, you need to go into the settings and enable the reverse proxy.

**Comment by ccpong-github** [comment]
Please advise on the attached png if it is correct because I have set the reverse proxy (as shown), but ComfyUI still do not show workflow after generating image.
![Uploading Screenshot - ComfyUI - Stable Diffusion.png…]()

**Comment by ccpong-github** [comment]
Please advise on the attached png if it is correct because I have set the reverse proxy (as shown), but ComfyUI still do not show workflow after generating image.
![Screenshot - ComfyUI - Stable Diffusion](https://github.com/ModelSurge/sd-webui-comfyui/assets/158038712/f91c1ed5-f132-4326-bb45-21fb0df4234f)

**Comment by PladsElsker** [comment]
Yes, the "reverse proxy: always" is correct. You might want to try the different interprocess communication protocols (filesystem/shared memory) to see if this changes anything. 

I am not sure I understand the issue fully, is there any ComfyUI interface shown at all in the accordions of the txt2img/img2img tabs? What about the ComfyUI tab? 

Have you tried reloading the frontend with the reload button?

**Comment by ccpong-github** [comment]
Thanks for your advise. Surely, I have ComfyUI interface in txt2img / img2img tabs and ComfyUI tab. I am loading Automatic 1111 in google colab with MacOS. Please see below attached PNG files for the ComfyUI tabs mentioned above (the status after I generated a image in img2img). Thanks.

![Screenshot Stable Diffusion ComfyUI txt2img](https://github.com/ModelSurge/sd-webui-comfyui/assets/158038712/d1c6a2ee-8eaa-4448-962c-03326f03cfae)

![Screenshot Stable Diffusion ComfyUI img2img](https://github.com/ModelSurge/sd-webui-comfyui/assets/158038712/5f1c536d-9242-4931-bb4d-ad18bae275b9)

![Screenshot Stable Diffusion ComfyUI Tab](https://github.com/ModelSurge/sd-webui-comfyui/assets/158038712/b39589cb-f6ed-41be-a812-dc6e6ef4c98c)

**Comment by PladsElsker** [comment]
I see some misbehaving UI in the tab, there should be either nothing or ComfyUI. If I remember correctly, there was a compatibility issue with the mov2mov extension because it was duplicating elemids. 

Can you try disabling the mov2mov extension? 
If it still doesn't work, are there any errors in the console?

**Comment by PladsElsker** [comment]
Aha, found it: #176

**Comment by PladsElsker** [comment]
Closing this as not planned because it seems to be related to the mov2mov extension issue. If you have another issue unrelated to the extension conflict with mov2mov, you can reopen this issue or open another one.
