### ISSUE TITLE
[UI Compatibility] ComfyUI elements use too much dead space

### ISSUE THREAD

**Issue by alfonslm** [ModelSurge/sd-webui-comfyui#214]
The UI of the ComfyUI plugin is incompatible with Infinite Image Browser because it have a large block of blank UI on the same page (and almost all pages) that blocks the UI of the image browser
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/10770782/d48a92d0-7994-411a-a8b3-3343ed2613de)

I would expect at minimum to have the option to remove the ComfyUI UI elements from specific pages in the settings or more reasonable, enable it where it makes sense.

**Comment by PladsElsker** [comment]
The extension is incompatible with mov2mov, this is not how the UI is supposed tp look like. The problem is on their side and author is apparently unresponsive. See #176
