### ISSUE TITLE
save workflow? how :(

### ISSUE THREAD

**Issue by 4lt3r3go** [ModelSurge/sd-webui-comfyui#219]
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/44883288/0b7a92e0-5abe-4527-a49d-5b18094766b8)
 whenever i save a workflow in external comfy setup and the drag and drop, i always have to connect this 2 modules.
is there a way to save the workflow as is right inside auto? so i have this 2 modules already connected?

**Comment by 4lt3r3go** [comment]
whenever it loads the entire extention, the comfy menu disappear after few seconds.
i can drop in a workflow, sure, but i alwasy have to connect those 2 modules.
doing this everyday

**Comment by PladsElsker** [comment]
I think you can hit `ctrl + s` to save a workflow inside A1111 to save with the new custom nodes. Make sure your cursor is inside the mini ComfyUI IFrame in which you want your workflow saved.

**Comment by PladsElsker** [comment]
The sidebar was hidden because there is so little space in these tiny IFrames, but all the shortcuts should still work.

**Comment by 4lt3r3go** [comment]
> I think you can hit `ctrl + s` to save a workflow inside A1111 to save with the new custom nodes. Make sure your cursor is inside the mini ComfyUI IFrame in which you want your workflow saved.

thank you! the ctrl+s saved me months of clicks
