### ISSUE TITLE
Bug: A strange UI appears on every tab.

### ISSUE THREAD

**Issue by Enchante503** [ModelSurge/sd-webui-comfyui#220]
A strange UI appears on every tab.
![UI2](https://github.com/ModelSurge/sd-webui-comfyui/assets/125081727/38f19cba-310b-467d-81e1-7e94b4c0d81a)

**Comment by PladsElsker** [comment]
Do you have mov2mov installed?

**Comment by Enchante503** [comment]
yes
Is that the cause? Some kind of conflict?

**Comment by PladsElsker** [comment]
Yes. If I remember correctly, the cause is that some elem_ids in their components are duplicates of existing ones in the webui, which we are using.

**Comment by PladsElsker** [comment]
#176
