### ISSUE TITLE
[feature request] add a button in the settings to automatically update ComfyUI

### ISSUE THREAD

**Issue by John-WL** [ModelSurge/sd-webui-comfyui#23]
Right now, we can only update ComfyUI by going to the installation and git-pulling, which is annoying. This should be a "single button click" feature. 
I'm thinking of adding it to the settings tab. 
Not sure where else would be more appropriate.

**Comment by anne43983959** [comment]
Looking forward to the early launch of this feature

**Comment by ljleb** [comment]
https://github.com/ltdrdata/ComfyUI-Manager has a button to update comfyui.
Should we also add a button to the ui, or instead install comfyui manager by default for new installs?

Install ComfyUI-Manager by default:
- creates a hard dependency on the extension for anyone wanting to update using the extension

Update button:
- more code in the extension, but comfyui does not need any extension to be able to update

I think we can close this issue as not planned and redirect users to the comfyui-manager tab. We should add an option to install it when setting up the extension, or even after installing comfyui, as it is a generally useful extension.

**Comment by John-WL** [comment]
I think we should at least update ComfyUI and its dependencies if the user has specified the flag `update-all-extensions` in the webui.

**Comment by John-WL** [comment]
I agree. We can suggest to new users to install the manager, and close this issue.

**Comment by ljleb** [comment]
If anyone is using the same comfyui install as a standalone, on top of sometimes letting the extension launch it, it may not be what they want. I believe we should aim to support more versions of comfyui instead of updating comfyui with the extension.

**Comment by John-WL** [comment]
Should we prevent the `--update-all-extensions` flag from updating it, then? People who install ComfyUI with the extension may later want to launch it in standalone for various reasons.

**Comment by ljleb** [comment]
If comfyui is installed within the extension, I think it's fine, but if it's installed outside of the webui somewhere else, then I'd consider it a bug.

What about this: some people never used comfyui before installing the extension. For these people, it may be better if we update it with the webui.

**Comment by ljleb** [comment]
Button to update comfyui was added a while ago in the settings.
