### ISSUE TITLE
"main.py" file missing

### ISSUE THREAD

**Issue by KAMIKAZZE112** [ModelSurge/sd-webui-comfyui#24]
When i tried to install the extension the following errors appeared:
![image](https://user-images.githubusercontent.com/128089378/232384297-cbd61d8c-6f16-4ddf-9e02-b0352954a67d.png)
As i can see its because the file "main.py" is missing, but why? its a fresh installation (i installed the extension from URL).
Also, the ComfyUI page in Automatic appears, but its totally empty.
![image](https://user-images.githubusercontent.com/128089378/232388663-fc07fba3-9ff4-4b09-9bc9-ffa52e69eb08.png)

**Comment by KAMIKAZZE112** [comment]
lul, i tried to reinstall the extension and new errors appeared:
![image](https://user-images.githubusercontent.com/128089378/232391472-1d6b9532-af81-4fb6-9767-e6736114deab.png)

**Comment by KAMIKAZZE112** [comment]
And running "install_comfyui.py" directly throws this error:
![image](https://user-images.githubusercontent.com/128089378/232393273-007b1111-fc6d-44e8-b957-4db186db2ef3.png)

**Comment by John-WL** [comment]
Sorry for the late reply, I did not get notified for this issue. 

Did you try installing it from the extension's tab? 

To fix the "No module named git" error, you can run `pip install GitPython`. 
If you have multiple versions of python on your pc, running the script with just "python" can also end up using the wrong version. Make sure you're using the right pip and python install in the command line. 

You technically don't need to run anything in the command line, though. The intended way of installing it is from the webui's extension page. Then, you go in the tab, and you will see a setup guide and a button for installing everything automatically in case you need that. 

If you didn't do that, I'd suggest trying to uninstall your current version, and try the intended way.

**Comment by KAMIKAZZE112** [comment]
Oh don't worry about the late reply, I will try to do what you say and I will put whatever I get

**Comment by KAMIKAZZE112** [comment]
I was fanally able to solve all the errors, if someone else just get these errors you have to check the following points:

- You need to have only one version of Python, its recommended to only install the 3.10.6 version because lattest versions can cause some errors

- In the stabble-diffusion-webui folder, open with Notepad the file "webui-user.bat" and, in the line "set PYTHON=" you have to copy the rute of your python instalation, for default is: "C:\Users\(Change this part with your pc user name)\AppData\Local\Programs\Python\Python310\python.exe" and then save the file
![image](https://user-images.githubusercontent.com/128089378/235050426-f0aa8867-b0e5-43db-abe3-a334de5ac1f0.png)

If nothing works, you have to delete the "stable-diffusion-webui" folder and clone it again: git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
After this, make sure to do the previous tip
Dont forget to backup your models, LoRAs, embeddings, extensions or whatever important things you have, and put it again inside the new stable diffusion folder

This is the way i was able to solve the problem, hope this helps someone in the future ( ﾟдﾟ)つ Bye

**Comment by John-WL** [comment]
Glad you were able to fix it 👍
