### ISSUE TITLE
Tab is empty when using headless server

### ISSUE THREAD

**Issue by jjohare** [ModelSurge/sd-webui-comfyui#27]
I have Automatic1111 running on a remote server in the building, accessible on the local network. That UI loads as expected. I can start main.py in ComfyUI with --listen [address] and then open the ComfyUI remotely as expected. I have added the path and necessary switch --listen [address] to the settings for the plugin and reloaded with successful console:

Launching ComfyUI with arguments: --listen [address] --port 8188
Total VRAM reported here
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 GPU here
Using xformers cross attention
Starting server

To see the GUI go to: http://192.168.0.51:8188

and in this state I can see both the Automatic UI, and the ComfyUI on their relevant remote ports.

Clicking on the tab does not load the interface in either firefox or Edge.

**Comment by John-WL** [comment]
We added comfyui flag forwarding from a1111. I think the issue is that you are passing the url and port flags directly to comfyui. 

If you want to pass flags to comfyui, you can pass `--comfyui-[flag]` to your a1111 args, where `[flag]` is a comfyui flag.

For example, you would use `--comfyui-port 8818` as an argument to your a1111 launch script in order to start comfyui on that port.

**Comment by jjohare** [comment]
Thanks, this feels closer. I can set the port with comfy-port but obviously --listen is just a flag here. In comfyui I can pass the IP address in too which is required for my setup.

python ./main.py --listen 192.168.n.n

**Comment by John-WL** [comment]
To pass the url to comfyui, you also need to pass the url in the forwarded -listen flag, which is `--comfyui-listen [url]`, where `[url]` is your url. 

You don't need to start comfyui manually, the extension is supposed to start it on its own through the webui.

**Comment by John-WL** [comment]
here's a list of the current forwarded comfyui flags at the time of writing, if you need other flags:
--comfyui-port
--comfyui-listen
--comfyui-dont-upcast-attention
--comfyui-use-split-cross-attention
--comfyui-use-pytorch-cross-attention
--comfyui-disable-xformers
--comfyui-highvram
--comfyui-normalvram
--comfyui-lowvram
--comfyui-novram
--comfyui-cpu

**Comment by jjohare** [comment]
I thought I understood that, but --comfyui-listen {ip address] errors as and unrecongnized argument. Thanks though I'll keep trying

**Comment by ljleb** [comment]
> parser.add_argument("--comfyui-listen", action='store_true', default=None)

Yeah the option is listed as a flag, but it should accept str. Needs to be fixed

**Comment by jjohare** [comment]
I did see that. Glad I am reporting an actual bug tbh! Thanks

**Comment by ljleb** [comment]
@John-WL if you're busy I can take this one, it should take 5 minutes.

**Comment by John-WL** [comment]
yes you can do it

**Comment by ljleb** [comment]
This took a little bit more tinkering that I thought. @jjohare does it make sense for your use case to specify a different address for the webui server and the address used by the extension? If you know one thing or two about networking, I'd like to know if you think it makes sense to be able to specify 2 different addresses (1 for the ComfyUI server, and 1 for the webui client to refer to the ComfyUI server). I added an option for the address used by the client that falls back on the server URL, but maybe this is unnecessary.

**Comment by jjohare** [comment]
I don't think so, they're both on the same system for ME, but they could hypothetically be separated out onto two machines. I feel that would imply parallelisation which seems like it's a more complex proposition. So long as images came back to the UX from both nodes through the UX it might be a nice provision though.

**Comment by ljleb** [comment]
IIIUC there are 4 addresses here at play:
- 2 for the webui: the address used to refer to the webui from within the webui, and the address used to refer to the webui from your web client
- 2 for ComfyUI: the address used to refer to ComfyUI from within ComfyUI, and the address used to refer to ComfyUI from your web client

IIUC, these could all be different. Is that the case for your setup, or there exist a way to refer to each of the webui and ComfyUI using a single url?

For example, in the case of passing `--listen 0.0.0.0` to comfyui, it seems that I need to use 127.0.0.1 to refer to it from a web client for it to load (`0.0.0.0:8188` doesn't work). My question was, are there other cases like this that would not be trivial? If so, we probably need a separate config value for the url used by the web client.

**Comment by jjohare** [comment]
In a cloud cluster context yes there could be 4, agreed  I am using this in an intranet context so this collapses to either 1 or 2. I normally use1 as I can reference localhost for webui and comfy using the same intranet "local network" IP. One is therefore fine for my issue but does not generalise to the possible 4 that a cloudy cluster implies for your plugin.

**Comment by ljleb** [comment]
Thanks, I'll take your suggestion.

By default if `--listen 0.0.0.0` is passed to comfyui, we will fallback to 127.0.0.1. The behavior can be overridden by setting the client url explicitly through the command line or through the extension settings.

**Comment by jjohare** [comment]
I have tested this in a cloud system with the following command style (adapt for your needs):
Start-Process -NoNewWindow -FilePath 'ssh' -ArgumentList '-L 7860:localhost:7860 -L 8188:localhost:8188 login@$IP
It works great now: Also need to add --listen and the local IP into the comfyui extensive boxes as discussed above.

**Comment by ljleb** [comment]
Thanks for testing, glad it works now.

> Also need to add --listen and the local IP into the comfyui extensive boxes as discussed above.

Is that unexpected? What would you expect to see if that is the case?

**Comment by jjohare** [comment]
Apologies, that is expected, I didn't even try it without. I left this note for people to follow later. Everything works.
