### ISSUE TITLE
extend support

### ISSUE THREAD

**Issue by zethfoxster** [ModelSurge/sd-webui-comfyui#28]
to vladmandic fork of auto1111, its equally as popular as the main fork if not exceedingly at this point.
currently the tab sizing is incorrect and covers the vladmandic tabs when you switch to comfy.

**Comment by zethfoxster** [comment]
editing the style css to  top:145 ended up a perfect fit for me, ideally this should be something you could adjust in settings.

**Comment by ljleb** [comment]
The front-end code needs a bit of a revamp. It is not perfect at the moment, as if you install too many extensions the height of the tabs selection region will be too great, it will also not work. We are open to contributions on this front.

**Comment by zethfoxster** [comment]
there's 4 completely different forks of automatic1111 now, it might be very tough to make a solution that works properly in them all, other than doing as i did and manually editing the css for the tab or making the tab size boarder resizable. I'm not that good with web stuff... wish i could be more help.

**Comment by John-WL** [comment]
I found a way to do it dynamically with the webui, but it needs to be tested on vladmandic's webui as well. I'll make a pr for now

**Comment by John-WL** [comment]
I'm pretty sure there's a way to update the tab height by setting up proper proxy objects, but I did a simple polling implementation for now.
