### ISSUE TITLE
[feature request] redirect webui output to comfy

### ISSUE THREAD

**Issue by John-WL** [ModelSurge/sd-webui-comfyui#48]
One really cool thing that could be done would be to create an alwayson script "redirect output to ComfyUI" or something like that, and then use a node "Webui Output" for using that output image. If the script is enabled, it redirects the output to ComfyUI, and starts the workflow. We could also add "Webui Save Img2Img", "Webui Save Txt2Img" and "Webui Save Extras" for outputing images in the same place as A1111 would. We could also append the workflow.json data to the image metadata to enable complex and reproduceable  A1111/ComfyUi workflows.

**Comment by John-WL** [comment]
This could be super handy for automating custom image postprocessing.

**Comment by jasoncow007** [comment]
cant agree wiht more,,,,right now it is likely just combined together
