### ISSUE TITLE
SyntaxError: Unexpected non-whitespace character after JSON at position 4

### ISSUE THREAD

**Issue by GivenChief** [ModelSurge/sd-webui-comfyui#65]
Very often I have this error.

Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Automatic1111 WebUI Version: ## 1.4.1
Commit hash: f865d3e11647dfd6c7b2cdf90dde24680e58acd8
![error](https://github.com/ModelSurge/sd-webui-comfyui/assets/130767370/335d8274-6ea6-4795-8968-1bccc865cfbd)

**Comment by ljleb** [comment]
What are the steps to reproduce it? Please tell us what to do to reproduce it, otherwise there is no way I can debug this.

Does the error trigger randomly without you doing anything? Or do you have to click in the ui somewhere? Please tell us what to do to reproduce the bug.

**Comment by ljleb** [comment]
What are the steps to reproduce it? Please tell us what to do to reproduce it, otherwise there is no way I can debug this.

Does the error trigger randomly without you doing anything? Do you need to have a certain node configuration in comfyui? Are some of the settings necessary to get the error? Or do you have to click in the ui somewhere? Please give us a step by step minimal reproduction method for the error to appear.

**Comment by John-WL** [comment]
Also, are you on windows or on linux?

**Comment by John-WL** [comment]
I think these are the only places where we parse json right now:
https://github.com/ModelSurge/sd-webui-comfyui/blob/c8151d3d76a839b061a37f22eb0c981f1123983d/lib_comfyui/comfyui_adapter.py#L24
https://github.com/ModelSurge/sd-webui-comfyui/blob/c8151d3d76a839b061a37f22eb0c981f1123983d/lib_comfyui/async_comfyui_loader.py#L40

**Comment by GivenChief** [comment]
> What are the steps to reproduce it? Please tell us what to do to reproduce it, otherwise there is no way I can debug this.
> 
> Does the error trigger randomly without you doing anything? Do you need to have a certain node configuration in comfyui? Are some of the settings necessary to get the error? Or do you have to click in the ui somewhere? Please give us a step by step minimal reproduction method for the error to appear.

1. "What are the steps to reproduce it?": startup the A1111 server, wait until local link appears, ComfyUI tab, Load Default template, simple positive and negative prompt, press Queue Prompt - the error appears.
2. "Does the error trigger randomly without you doing anything?" - once I generated image by ComfyUI, but after next update the error appers. Restarting server and OS doesn't help.
3. "Do you need to have a certain node configuration in comfyui?" - The error appears even in default template.
4. "Are some of the settings necessary to get the error?" - No, every setting is by default, I changed nothing.
5. "Or do you have to click in the ui somewhere?" - only button "Queue Prompt".
6. "give us a step by step minimal reproduction method for the error to appear" - at the point 1.
7. "are you on windows or on linux?" - Win11 Home, 22H2, x64, NVIDIA GeForce RTX 2060. A1111 WebUI works perfectly.
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/130767370/9b334972-d90a-4d00-bd89-82a7acfe4c60)

**Comment by John-WL** [comment]
Last update was the addition of the new node for saving images on the webui paths directly, so I'm confident that the error is somehow related to the lines I mentionned.

**Comment by John-WL** [comment]
if you could also show the error you are getting in the console, that would be a huge help as well

**Comment by GivenChief** [comment]
> if you could also show the error you are getting in the console, that would be a huge help as well

I made kind of investigation, evidences on screens. )
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/130767370/f39b868d-07ec-4fe5-b298-84eeb4cfd142)
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/130767370/c6a15159-8972-4d06-af8f-314733e1b991)
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/130767370/565a37cb-d3b0-421c-9ae5-ece7cec4e275)
Console says, something listens to 127.0.0.1:8188 but I see pyton.exe PID only. Maybe, I should manually change port 8088 in config file of Comfy UI or shouldn't I? If so, where is this config file?

**Comment by ljleb** [comment]
> Maybe, I should manually change port 8088 in config file of Comfy UI or shouldn't I? If so, where is this config file?

IIUC, it seems that comfyui wasn't closed properly on your system after it ran into an error. I believe you can safely kill the process, if it isn't another service you put on that port.

If you already have something running on port 8188, then to change the comfyui port, you can go to the settings of the extension and put `--port 8088` in the additional command line arguments field. Alternatively, you can pass `--comfyui-port 8088` to the webui, it should redirect it to the webui.

**Comment by GivenChief** [comment]
> > Maybe, I should manually change port 8088 in config file of Comfy UI or shouldn't I? If so, where is this config file?
> 
> IIUC, it seems that comfyui wasn't closed properly on your system after it ran into an error. I believe you can safely kill the process, if it isn't another service you put on that port.
> 
> If you already have something running on port 8188, then to change the comfyui port, you can go to the settings of the extension and put `--port 8088` in the additional command line arguments field (and then reload the ui). Alternatively, you can pass `--comfyui-port 8088` to the webui, it should redirect it to the webui.

You are completely right. I noticed that after closing A1111 server in Task Manager one python.exe process still exists. After killing it manually and restarting A111 WebUI server there is no error during generating images in Comfy UI. 
Problem solved without changing ports.
Thank you a lot! I hope, that this tread will help other people and at least it will appear in Google Search page instead of boring you. )
