### ISSUE TITLE
[BUG]: Opening multiple webui clients simultaneously has unexpected behavior

### ISSUE THREAD

**Issue by ljleb** [ModelSurge/sd-webui-comfyui#72]
Opening multiple browser windows at http://localhost:7860 makes both web clients use the workflows from the last open client. Both clients should use their respective workflows, there shouldn't be any cross talk between the clients.

**Comment by John-WL** [comment]
for me later
https://github.com/ModelSurge/sd-webui-comfyui/pull/63/files#diff-b392fd2ef2cf5920b8d60bf44eac3f8f1f51a231f3e319d75f9c634f2d1facd9R88

**Comment by John-WL** [comment]
Maybe we could require users to specify what launches a group of workflows? 

For examle, in the txt2img and img2img tabs, that would be the "generate" button. In extras, same thing. 

Maybe we could add an interface for that? 

Each time a registered UI component is clicked, the associated webui id would be selected.

**Comment by John-WL** [comment]
The best way to handle this is to select the id based on which UI made the request directly in python, but I don't know if we can do this with the gradio interface.

**Comment by ljleb** [comment]
I think a simpler solution is to create a gradio component that receives the random uuid from the client side (i.e. using a ui event). Then, from python, we can pass this id along with the rest of the components in `process` to detect the current webui id.
