### ISSUE TITLE
[Feature Request]: Add comfyui workflows to webui PNG Info metadata

### ISSUE THREAD

**Issue by ljleb** [ModelSurge/sd-webui-comfyui#73]
Loading an image generated with the extension should also restore the state of all used comfyui workflows.

Also, drag-and-dropping an image into a workflow should load the appropriate workflow from the metadata, but only for that workflow.

**Comment by John-WL** [comment]
I also want to load the right workflow of an image if it is dragged onto one of the workflow types. For example, its preprocess-latent workflow would be loaded into the preprocess-latent-img2img workflow type, despite the image having multiple workflow type in the metadata. I believe this is actually easy to implement, but maybe we should open a new issue for that.
