### ISSUE TITLE
[BUG]: postprocessing workflow overwrites browser local storage

### ISSUE THREAD

**Issue by ljleb** [ModelSurge/sd-webui-comfyui#75]
The last workflow I put together constantly gets overwritten in the browser local storage because auxiliary workflows (like postprocessing) also saves to the local storage.

![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/32277961/5dfa10f3-dd4f-45da-b444-703923743567)

**Comment by John-WL** [comment]
we fixed it yesterday

**Comment by ljleb** [comment]
We haven't fixed it yet. We should close issues when main has the fix

**Comment by John-WL** [comment]
lol
