### ISSUE TITLE
[BUG]: WSL support

### ISSUE THREAD

**Issue by ljleb** [ModelSurge/sd-webui-comfyui#76]
For some reason, the mix of process/thread/asyncio used by the extension hangs on WSL. In particular, it seems that the thread in the comfyui process responsible for responding to webui requests hangs either here:

https://github.com/ModelSurge/sd-webui-comfyui/blob/27709d8451ec1427e1fa68244005c558c1be6c82/lib_comfyui/parallel_utils.py#L46

or here:

https://github.com/ModelSurge/sd-webui-comfyui/blob/27709d8451ec1427e1fa68244005c558c1be6c82/lib_comfyui/parallel_utils.py#L53

It is possible that it also hangs there on bare metal linux, however I do not have a machine to test it. If anybody could confirm whether it works or not, I'd appreciate it.

**Comment by John-WL** [comment]
We might have found a solution for supporting WSL. We think the threading code is working fine when ComfyUI talks to the Webui, and not the opposite. So the idea would be to prevent `@ipc.confine_to('comfyui')` anotations. If we want the Webui to talk to ComfyUI, we will add routes in the server for running specific processes or queries instead. 

This should fix the deadlock issues.
