### ISSUE TITLE
Compatibility issues with google collab

### ISSUE THREAD

**Issue by John-WL** [ModelSurge/sd-webui-comfyui#9]

**Comment by John-WL** [comment]
for reference:
https://colab.research.google.com/github/comfyanonymous/ComfyUI/blob/master/notebooks/comfyui_colab.ipynb

**Comment by ljleb** [comment]
Maybe consider compatibility with this extension? https://github.com/Bing-su/sd-webui-tunnels
Or this one https://github.com/camenduru/sd-webui-tunnels

**Comment by John-WL** [comment]
are we still considering to implement this?

**Comment by ljleb** [comment]
Colab works but you need a pro account for a ui session to not get randomly disconnected. I think so, but maybe just not a priority right now.
