### ISSUE TITLE
Postprocess nodes not working in SD.Next 

### ISSUE THREAD

**Issue by John-WL** [ModelSurge/sd-webui-comfyui#90]
Last update is using a new callback `postprocess_batch_list` that is not yet implemented in SD.Next. 

We might want to make a PR in SD.Next repo.

**Comment by ljleb** [comment]
ref to issue in sd next: https://github.com/vladmandic/automatic/issues/1892

**Comment by ljleb** [comment]
Once the PR in sd next reaches master we can close this issue.
