### ISSUE TITLE
[BUG] In the ComfyUI extension tag, ComfyUI rendering error. 

### ISSUE THREAD

**Issue by GalileoFe** [ModelSurge/sd-webui-comfyui#92]
I tried using chrome and Edge and it is the same display, the comfyUI interface is at the bottom of the page instead of in the middle.
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/138156577/a0c726e2-dd87-4bdb-8bcb-8cd700d662ca)

**Comment by ljleb** [comment]
The only browsers we have heavily tested the extension against so far are firefox and chrome. I'm not sure how easy it would be to extend support for edge. Please consider using one of chrome or firefox as a workaround for now.

**Comment by ljleb** [comment]
The last time I ran the extension using chrome, there was no such issue. Is your browser up to date? which version of the webui are you using?

**Comment by jojushin** [comment]
> The last time I ran the extension using chrome, there was no such issue. Is your browser up to date? Please note that the extension requires webui>=1.5.1. You seem to be currently on 1.5.0
me too, 1.5.1, the comfyUI interface is at the bottom of the page instead of in the middle.

**Comment by GalileoFe** [comment]
> 上次我使用 chrome 运行扩展程序时，没有这样的问题。您的浏览器是最新的吗？请注意，该扩展需要webui>=1.5.1。您当前似乎在 1.5.0 上

thanks for your help.

**Comment by ljleb** [comment]
@GalileoFe did you fix this issue? Please let us know what you did. It appears you were not the only one facing this, so it would be helpful to others if you could share any information you have.

**Comment by ljleb** [comment]
Closing this for now, but please let us know if this is still a problem.

**Comment by GalileoFe** [comment]
its all right, No Problem, Thanks for your hard working.
