### ISSUE TITLE
ComfyUI can't launch!

### ISSUE THREAD

**Issue by baijunty** [ModelSurge/sd-webui-comfyui#93]
Printing log shows it stuck at async_comfyui_loader file main function  ipc.start_callback_listeners() statement。
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/8980568/2016caed-2f75-414f-b65f-ad5e5ee7ba42)
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/8980568/99d8d9a3-0369-4183-bed1-8c80e6ad2cfa)
ComfyUI  already installed at extensions/sd-webui-comfyui/ComfyUI

**Comment by John-WL** [comment]
What is your OS?

**Comment by baijunty** [comment]
> fedora 38

**Comment by ljleb** [comment]
This is the same behavior we observe on wsl. I will be able to look into this issue with plads this week. I don't know how long it will take to fix, as this needs a redesing of the part of the extension that handles sending information from the webui server to the comfyui server.

**Comment by ljleb** [comment]
@baijunty can you try with the latest version? we just pushed a fix for WSL, it is possible that it also fixes linux

**Comment by HanHollander** [comment]
had the same issue, fixed now. Great work! thanks
